### ISSUE TITLE
The 50.000 example is very slow on my machine, why?

### ISSUE THREAD

**Issue by tonix-tuft** [adrilo/spout-pdo-example#2]
When I run `php index.php` these are the some of the outputs I got:

Fetch mode: batch
**Elapsed time: 100.74s**
Memory peak: 2MB

Fetch mode: batch
**Elapsed time: 95.23s**
Memory peak: 2MB

Of course, Spout does not behave consistently because in your example it should take less than 10 seconds...

Any idea on why does Spout takes too much time to write the Excel file?

I use PHP 7 with MySQL Native Driver, PDO and Spout v2.1.0

**Comment by adrilo** [comment]
Are you sure you are dealing with 50,000 rows and not 500,000 rows?

**Comment by tonix-tuft** [comment]
Yes, with 50.000. I left everything as is after I cloned the repo, and I
checked the generated Excel file and DB both have 50.000 rows. What it
could be?

**Comment by adrilo** [comment]
Maybe you're running it with XDebug enabled? This may slow down the execution a lot.
I tried re-running the script and still get the numbers listed in the README. So definitely something wrong with your machine.

**Comment by tonix-tuft** [comment]
You were right, I tried to disable xdebug and performance changed drastically. For 50,000 rows:

Fetch mode: batch
Elapsed time: 7.4s
Memory peak: 2MB

Thank you!
